-- 코드를 입력하세요


SELECT F.FLAVOR 
FROM FIRST_HALF F
JOIN JULY J
ON F.SHIPMENT_ID = J.SHIPMENT_ID
ORDER BY F.TOTAL_ORDER+(SELECT SUM(TOTAL_ORDER) FROM JULY WHERE F.FLAVOR = FLAVOR GROUP BY FLAVOR) DESC
LIMIT 3