-- 코드를 작성해주세요

WITH MAXLENGTH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
)
SELECT I.ID , N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
JOIN MAXLENGTH M ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.LENGTH
ORDER BY I.ID
